runtime: php83

build_env_variables:
  GOOGLE_COMPOSER_VERSION: 2.6.6

env_variables:
  APP_URL: $APP_URL
  APP_KEY: $APP_KEY
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_PATH: /tmp/cache
  SESSION_DRIVER: cookie
  APP_NAME: Vintage VW Decoder
  DB_CONNECTION: 'turso'
  DB_URL: $DB_URL
  DB_ACCESS_TOKEN: $DB_ACCESS_TOKEN
  DB_FOREIGN_KEYS: 'true'
  DB_STICKY: 'true'

handlers:
- url: /(.*\.(gif|png|jpg|css|js))$
  static_files: public/\1
  upload: public/.*\.(gif|png|jpg|css|js)$

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
