runtime: php
env: flex

runtime_config:
  operating_system: "ubuntu22"
  document_root: "public"

build_env_variables:
  GOOGLE_COMPOSER_VERSION: 2.5.8

env_variables:
  APP_URL: $APP_URL
  APP_KEY: $APP_KEY
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_PATH: /tmp/cache
  SESSION_DRIVER: cookie
  APP_NAME: Vintage VW Decoder
  DB_HOST: $DB_HOST
  DB_USERNAME: $DB_USERNAME
  DB_PASSWORD: $DB_PASSWORD
  DB_DATABASE: $DB_DATABASE
  MYSQL_ATTR_SSL_CA: $MYSQL_ATTR_SSL_CA

handlers:
- url: /(.*\.(gif|png|jpg|css|js))$
  static_files: public/\1
  upload: public/.*\.(gif|png|jpg|css|js)$

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
